# Generated by Django 5.2.13 on 2026-05-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0002_alter_player_guild_alter_player_race"),
    ]

    operations = [
        migrations.RenameField(
            model_name="skill",
            old_name="name",
            new_name="nickname",
        ),
        migrations.AlterField(
            model_name="player",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
